#!/bin/bash

# Criando o diretório local
mkdir -p local_dir

# Baixando os arquivos para o diretório local
curl -s -L -o local_dir/main https://github.com/universoflix/script/raw/main/main
curl -s -L -o local_dir/proxy https://github.com/universoflix/script/raw/main/proxy

# Dando permissão de execução
chmod +x local_dir/main local_dir/proxy

# Copiando os arquivos para o diretório /usr/bin
sudo cp local_dir/main /usr/bin/main
sudo cp local_dir/proxy /usr/bin/proxy

# Executando badvpn-udpgw em uma nova sessão de screen
screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7100 --max-clients 10000 --max-connections-for-client 5 --client-socket-sndbuf 10000

clear && echo -e "\033[1;31mInstalado com Sucesso! A porta UDP 7100 foi aberta com sucesso. Execute: \033[1;32mmain\033[0m para entrar no painel."
